rootProject.name = "ecom-asynchronous"
include("api-gateway")
include("mitarbeiter-service")
include("bestell-service")
include("bezahl-service")
include("discovery-server")
include("inventar-service")
include("produkt-service")
include("user-service")
include("zustell-service")
